[package]
name = "norgolith"
version = "0.1.0"
edition = "2021"
authors = ["NTBBloodbath <bloodbathalchemist@protonmail.com"]
license = "GPL-3.0"
readme = "README.md"
description = "The monolithic Norg static site generator"
repository = "https://github.com/NTBBloodbath/norgolith"
keywords = ["static", "site", "generator", "blog", "norg"]

include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["deprecated", "derive", "env", "wrap_help"] }
comfy-table = "7.1.1"
hyper = { version = "=0.14.28", features = ["runtime", "server", "http1", "http2"] }
tera = "1.19.1"
tokio = { version = "1.37.0", features = ["fs", "time", "rt-multi-thread", "macros"] }
tree-sitter = "0.22.5"
tree-sitter-norg = "0.1.1"
tree-sitter-norg-meta = { git = "https://github.com/nvim-neorg/tree-sitter-norg-meta" }

[profile.optimized]                 # Size optimizations that will hurt build speed
inherits = "release"                # Which profile we inherit
opt-level = "z"                     # Optimize for size
codegen-units = 1                   # Build speed -> Executable size
strip = true                        # Remove debug symbols
