[package]
name = "norgolith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["deprecated", "derive", "env", "wrap_help"] }
comfy-table = "7.1.1"
tera = "1.19.1"
tree-sitter = "0.22.5"
tree-sitter-norg = "0.1.1"
