name: Bug Report
description: Report a bug encountered while using Norgolith.
title: "[Bug]: "
labels: [bug]
body:
  - type: checkboxes
    id: issue-prerequisite
    attributes:
      label: Issues
      options:
        - label: I have checked [existing issues](https://github.com/NTBBloodbath/norgolith/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and there no existing ones with the same bug report.
          required: true

  - type: input
    attributes:
      label: "Operating System"
      description: "Your current OS (Windows/Linux/MacOS/etc)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual Behavior"
      description: "A description of the actual behavior. Extra points if it includes images or videos."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Please describe how we can reproduce the issue."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Other information"
      description: "Other information that could be helpful with debugging."

  - type: dropdown
    id: help
    attributes:
      label: "Help"
      description: "Would you be able to resolve this issue by submitting a pull request?"
      options:
        - "Yes"
        - "Yes, but I don't know how to start. I would need guidance (check question below)"
        - "No"

  - type: textarea
    attributes:
      label: "Implementation help"
      description: "If you selected yes in the last question please specify what you would need help with in order to resolve the issue."
