name: build

on:
  push:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"
  pull_request:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Run
        run: cargo run -- --version

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Run
        run: cargo run -- --version
