name: format

on:
  push:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"
  pull_request:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Format code
        run: cargo fmt --all --verbose
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: autoformat with cargo"
          branch: ${{ github.ref }}
      - name: Push formatted files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
