name: lint

on:
  push:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"
  pull_request:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Lint
        run: cargo clippy -- --deny warnings
