name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      # Do not cancel the build process if any of them fails
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os_name: Linux-aarch64
            os: ubuntu-24.04
            target: aarch64-unknown-linux-musl
          - os_name: Darwin-x86_64
            os: macos-13
            target: x86_64-apple-darwin
          - os_name: Darwin-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        if: ${{ startsWith(matrix.platform.os_name, 'Linux') }}
        run: |
          sudo apt-get install -y pkg-config libssl-dev
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: lith
          changes-file: ""
          extra-files: |
            README.md
            LICENSE
          target: ${{ matrix.platform.target }}
