name: test

on:
  push:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"
  pull_request:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  nextest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Install nextest
        run: cargo install cargo-nextest
      - uses: Swatinem/rust-cache@v2
      - name: Test codebase
        run: cargo nextest run --features ci
